#!/bin/bash

MODELS_DIR="/m-pinotHD/echau18/bert/outputs"
MBERT_CONFIG="/m-pinotHD/echau18/bert/mbert/bert_config.json"

ARGS=( "$@" )

PREFIX=("${ARGS[0]}")
EPOCH_1_SIZE=("${ARGS[1]}")

eval "$(conda shell.bash hook)"
conda activate allentune

cd $MODELS_DIR/$PREFIX
pwd

for ep in 1 5 10 15 20; do
    STEP_COUNT=$((ep * EPOCH_1_SIZE))
    echo "Epoch $ep: $STEP_COUNT"
    mkdir epoch_"$ep"
    mv model.ckpt-"$STEP_COUNT".* epoch_"$ep"/
    cp $MBERT_CONFIG epoch_"$ep"/
    pytorch_transformers bert \
                         epoch_"$ep"/model.ckpt-"$STEP_COUNT" \
                         epoch_"$ep"/bert_config.json \
                         epoch_"$ep"/pytorch_model.bin
done
